project:
  type: website
  # output-dir: _site

website:
  title: "Group 5 - ISSS608 Project"
  navbar:
    left:
      - href: "Proposal.html"
        text: "Proposal"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Team_Member.qmd
        text: Team Members