project:
  type: website
  # output-dir: _site

website:
  title: "Group 5 - ISSS608 Project"
  navbar:
    left:
      - href: "Proposal.html"
        text: "Proposal"
      - href: "Meeting_Minutes.html"
        text: "Meeting Minutes"
      - href: "User_Guide.html"
        text: "User Guide"
    right: 
      - href: index.qmd
        text: Home
      - href: "Team_Member.html"
        text: Team Members