project:
  type: website
  output-dir: _site

website:
  title: "ISSS608 Project"
  navbar:
    left:
      - href: Proposal.qmd
        text: Proposal
    right: 
      - href: Team_Member.qmd
        text: Team Members